# Generated by Django 2.2.2 on 2019-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status_note',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=20),
        ),
    ]
