# Generated by Django 2.2.2 on 2019-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAB', '0003_auto_20190726_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status_note',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=20, null=True),
        ),
    ]
