# Generated by Django 2.2.2 on 2019-07-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAB', '0004_auto_20190726_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='SIF_complete',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SIF_pending',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Total_SIFs',
        ),
    ]
